language: node_js

node_js:
  - 6
  - 8
  - 10

sudo: required

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"

install:
  - npm ci

script:
  - npm run serve & npm run test:ci

notifications:
  email: false
