language: node_js
node_js:
- 6
- 8
- 10

sudo: required

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"

before_install:
  - npm install -g bower
  - npm install -g testem
  - npm install -g testcafe

install:
  - npm install
  - bower install

script:
  - npm run test:ci

notifications:
  email: false
